### ISSUE TITLE
Firefox Support

### ISSUE THREAD

**Issue by gluons** [sindresorhus/merge-windows#4]
I've tried your extension in my Firefox Nightly.  
It works well 😍 after I remove `"persistent": false` from `manifest.json` (Firefox hasn't supported it yet).

Maybe you can publish to [AMO](http://addons.mozilla.org/) when webextensions come to Firefox Stable. 🎉

**Comment by sindresorhus** [comment]
Sorry, no. I support Firefox with another extension of mine, and I don't have the best experience:

- Supporting another browser requires additional testing.
- Extra work publishing new releases.
- The Firefox Web Extensions API is not 100% compatible with the Chrome Extensions API.
- The AMO interface is annoying.
- AMO reviews are slow.
- AMO doesn't allow source maps which helps with debugging in production.
- AMO doesn't allow shipping frequent updates.
- AMO reviewers are annoying, too nitpicky, and inconsistent.
- Dumb Firefox users give bad reviews on AMO because extensions are updated too frequently.
- I don't use Firefox, nor care.

This project is open source. You are free to fork and publish a Firefox version under a different name.

**Comment by gluons** [comment]
OMG. 😱

OK. Can I fork your repo and publish to AMO? 😅

**Comment by iamstarkov** [comment]
Firefox users try this https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/
